name: rillgen2d
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - affine
  - atk
  - attrs
  - bidict
  - boost-cpp
  - branca
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - cfitsio
  - chardet
  - click
  - click-plugins
  - cligj
  - cryptography
  - curl
  - cycler
  - dbus
  - expat
  - fftw
  - folium
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - freetype
  - freexl
  - fribidi
  - gdal
  - gdk-pixbuf
  - geos
  - geotiff
  - gettext
  - ghostscript
  - giflib
  - glib
  - graphite2
  - graphviz
  - gtk2
  - gts
  - harfbuzz
  - hdf4
  - hdf5
  - icu
  - idna
  - imagemagick
  - jbig
  - jinja2
  - jpeg
  - json-c
  - kealib
  - kiwisolver
  - krb5
  - lcms2
  - libblas
  - libcblas
  - libclang
  - libcurl
  - libcxx
  - libdap4
  - libedit
  - libev
  - libffi
  - libgdal
  - libgfortran
  - libgfortran5
  - libglib
  - libiconv
  - libkml
  - liblapack
  - libllvm10
  - libllvm9
  - libnetcdf
  - libnghttp2
  - libopenblas
  - libpng
  - libpq
  - librsvg
  - libspatialite
  - libssh2
  - libtiff
  - libuuid
  - libwebp
  - libwebp-base
  - libxcb
  - libxml2
  - llvm-openmp
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mkl
  - mysql-common
  - mysql-libs
  - ncurses
  - nspr
  - nss
  - numpy
  - olefile
  - openjpeg
  - openssl
  - pango
  - pcre
  - perl
  - pillow
  - pip
  - pixman
  - pkg-config
  - poppler
  - poppler-data
  - postgresql
  - proj
  - pthread-stubs
  - pycparser
  - pyopenssl
  - pyparsing
  - pyqt
  - pyqt-impl
  - pyqt5-sip
  - pyqtchart
  - pyqtwebengine
  - pysocks
  - python
  - python-dateutil
  - python-engineio
  - python-socketio
  - python_abi
  - qt
  - rasterio
  - readline
  - requests
  - setuptools
  - six
  - snuggs
  - sqlite
  - tbb
  - tiledb
  - tk
  - tornado
  - tzcode
  - urllib3
  - wand
  - wheel
  - xerces-c
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxrender
  - xorg-libxt
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - zlib
  - zstd