name: rillgen2d
channels:
  - conda-forge
dependencies:
  - python>=3.10.*
  - streamlit>=1.18
  - gdal
  - coreutils
  - pillow>=9.5.0
  - folium
  - clang_osx-64
  - clangxx_osx-64
  - gfortran_osx-64


