name: rillgen2d
channels:
  - conda-forge
  - defaults
dependencies:
  - libffi
  - kealib
  - tornado
  - zlib
  - krb5
  - pcre
  - zstd
  - ca-certificates
  - libuuid
  - libpng
  - ncurses
  - cligj
  - bidict
  - libglib
  - c-ares
  - giflib
  - atk
  - hdf4
  - python_abi
  - pip
  - libopenblas
  - kiwisolver
  - libclang
  - geotiff
  - librsvg
  - ghostscript
  - openjpeg
  - xorg-libxdmcp
  - libxml2
  - xorg-libice
  - tbb
  - python-engineio
  - libev
  - folium
  - xorg-libsm
  - chardet
  - idna
  - xorg-libxrender
  - xorg-renderproto
  - poppler
  - pyopenssl
  - libdap4
  - libllvm9
  - xorg-xproto
  - requests
  - wheel
  - gts
  - libcxx
  - mkl
  - click
  - lcms2
  - tk
  - numpy
  - readline
  - xorg-libx11
  - libcblas
  - glib
  - libgdal
  - olefile
  - dbus
  - hdf5
  - gdk-pixbuf
  - imagemagick
  - libcurl
  - xerces-c
  - pycparser
  - branca
  - libgfortran
  - libpq
  - nspr
  - pixman
  - mysql-libs
  - jpeg
  - xorg-kbproto
  - libkml
  - tzcode
  - pango
  - tiledb
  - fonts-conda-ecosystem
  - pyparsing
  - pyqtwebengine
  - pysocks
  - xorg-libxt
  - harfbuzz
  - mysql-common
  - pyqt
  - sqlite
  - proj
  - cairo
  - fonts-conda-forge
  - click-plugins
  - gdal
  - markupsafe
  - poppler-data
  - freexl
  - cycler
  - fribidi
  - pillow
  - matplotlib-base
  - font-ttf-source-code-pro
  - libwebp-base
  - lz4-c
  - json-c
  - boost-cpp
  - urllib3
  - pthread-stubs
  - python-socketio
  - python
  - attrs
  - graphviz
  - jinja2
  - libtiff
  - pyqt-impl
  - icu
  - pkg-config
  - xorg-libxext
  - libedit
  - certifi
  - pyqt5-sip
  - libllvm10
  - geos
  - graphite2
  - font-ttf-inconsolata
  - libnghttp2
  - xorg-xextproto
  - libiconv
  - libwebp
  - llvm-openmp
  - xz
  - libgfortran5
  - curl
  - snuggs
  - brotlipy
  - perl
  - nss
  - bzip2
  - libxcb
  - xorg-libxau
  - python-dateutil
  - expat
  - gettext
  - libblas
  - liblapack
  - fontconfig
  - pyqtchart
  - libspatialite
  - libssh2
  - matplotlib
  - font-ttf-ubuntu
  - openssl
  - setuptools
  - wand
  - affine
  - fftw
  - gtk2
  - freetype
  - cryptography
  - font-ttf-dejavu-sans-mono
  - libnetcdf
  - jbig
  - rasterio
  - qt
  - cfitsio
  - cffi
  - six
  - postgresql
