name: rillgen2d
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
#  - _libgcc_mutex
#  - _openmp_mutex
  - affine
#  - alsa-lib
  - atk-1.0
  - attrs
  - boost-cpp
  - branca
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - cfitsio
  - chardet
  - click
  - click-plugins
  - cligj
  - cryptography
  - curl
  - cycler
  - dbus
  - expat
  - fftw
  - folium
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - freetype
  - freexl
  - fribidi
  - gdal
  - gdk-pixbuf
  - geos
  - geotiff
  - gettext
  - ghostscript
  - giflib
  - glib
  - glib-tools
  - graphite2
  - graphviz
  - gst-plugins-base
  - gstreamer
  - gtk2
  - gts
  - harfbuzz
  - hdf4
  - hdf5
  - icu
  - idna
  - imagemagick
  - jbig
  - jinja2
  - jpeg
  - json-c
  - kealib
  - kiwisolver
  - krb5
  - lcms2
  - ld_impl_linux-64
  - libblas
  - libcblas
  - libclang
  - libcurl
  - libdap4
  - libedit
  - libev
  - libevent
  - libffi
#  - libgcc-ng
  - libgcc
  - libgd
  - libgdal
  - libgfortran-ng
  - libgfortran5
  - libglib
#  - libgomp
  - libiconv
  - libkml
  - liblapack
  - libllvm11
  - libnetcdf
  - libnghttp2
  - libogg
  - libopenblas
  - libopus
  - libpng
  - libpq
  - librsvg
  - librttopo
  - libspatialite
  - libssh2
#  - libstdcxx-ng
  - libtiff
  - libtool
  - libuuid
  - libvorbis
  - libwebp
  - libwebp-base
  - libxcb
#  - libxkbcommon
  - libxml2
  - libzip
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mysql-common
  - mysql-libs
  - ncurses
  - nspr
  - nss
  - numpy
  - olefile
  - openjpeg
  - openssl
  - osgeo
  - pango
  - pcre
  - perl
  - pillow
  - pip
  - pixman
  - pkg-config
  - poppler
  - poppler-data
  - postgresql
  - proj
  - pthread-stubs
  - pycparser
  - pyopenssl
  - pyparsing
  - pyqt
  - pyqt-impl
  - pyqt5-sip
  - pyqtchart
  - pyqtwebengine
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - qt
  - rasterio
  - readline
  - requests
  - setuptools
  - six
  - snuggs
  - sqlite
  - tiledb
  - tk
  - tornado
  - tzcode
  - tzdata
  - urllib3
  - wand
  - wheel
  - xerces-c
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxrender
  - xorg-libxt
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - zlib
  - zstd