FROM continuumio/miniconda3:4.9.2
ENV TZ=US/Phoenix
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone
# Install applications we need
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3-gdal \
        gdal-bin   \
        libgdal-dev  \
        gcc \
        g++    
COPY . /root/
RUN conda update -n base -c defaults conda && \
    cd root && \
    conda env create -f environment_windows.yml
# Make RUN commands use the new environment:
SHELL ["conda", "run", "-n", "rillgen", "/bin/bash", "-c"]
WORKDIR /root
ENTRYPOINT ["conda", "run", "-n", "rillgen", "python", "rillgen2d.py"]